"""empty message

Revision ID: 0471a057557a
Revises: b8c6a6bc62c5
Create Date: 2018-07-20 15:52:54.794840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0471a057557a'
down_revision = 'b8c6a6bc62c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_geo_text_word_1_sentence_id', table_name='geo_text_word_1')
    op.create_foreign_key(None, 'geo_text_word_1', 'geo_text_sentence', ['sentence_id'], ['id'])
    op.create_index(op.f('ix_geo_text_word_2_content'), 'geo_text_word_2', ['content'], unique=False)
    op.create_index(op.f('ix_geo_text_word_3_content'), 'geo_text_word_3', ['content'], unique=False)
    op.create_index(op.f('ix_geo_text_word_4_content'), 'geo_text_word_4', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_text_word_4_content'), table_name='geo_text_word_4')
    op.drop_index(op.f('ix_geo_text_word_3_content'), table_name='geo_text_word_3')
    op.drop_index(op.f('ix_geo_text_word_2_content'), table_name='geo_text_word_2')
    op.drop_constraint(None, 'geo_text_word_1', type_='foreignkey')
    op.create_index('ix_geo_text_word_1_sentence_id', 'geo_text_word_1', ['sentence_id'], unique=False)
    # ### end Alembic commands ###
