"""empty message

Revision ID: 2c453b3f95a9
Revises: 
Create Date: 2018-07-09 19:56:28.962714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c453b3f95a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content', 'sentence', ['content'], unique=False, mysql_length=50)
    op.create_table('word_num',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=30), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('word_num')
    op.drop_index('idx_content', table_name='sentence')
    op.drop_table('sentence')
    # ### end Alembic commands ###
