"""empty message

Revision ID: b8c6a6bc62c5
Revises: 351c7be35783
Create Date: 2018-07-19 11:29:38.563102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c6a6bc62c5'
down_revision = '351c7be35783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ansj_word_content'), 'ansj_word', ['content'], unique=False)
    op.create_index(op.f('ix_jcseg_word_content'), 'jcseg_word', ['content'], unique=False)
    op.create_index(op.f('ix_jieba_word_content'), 'jieba_word', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jieba_word_content'), table_name='jieba_word')
    op.drop_index(op.f('ix_jcseg_word_content'), table_name='jcseg_word')
    op.drop_index(op.f('ix_ansj_word_content'), table_name='ansj_word')
    # ### end Alembic commands ###
